### ISSUE TITLE
Automate deployment process

### ISSUE THREAD

**Issue by maxcanna** [maxcanna/homeautomation#5]
Set up continuous deployment instead of manually pushing to production repository.
Think about completely deprecating `git` on production environment and setup an automated deployment process that does not leverage a git hook.

**TODO**
- [x]  Move git hook to bash script in `www` user home
- [x]  Copy `constants.js.dist` in `www` user home as `constants.js`
- [x]  Change ownership of `/var/www/homeautomation`
- [x]  Remove watch from `pm2` config params
- [x]  Add `www@maspberry` public key as deploy key to allow `git pull`
- [x]  Add deploy of `master` branch to ~~.gitlab-ci.yml~~ codeship #7

**Comment by maxcanna** [comment]
Watch removed in cc3616f6d5c9b4e97b07236bdf052dc6348d4147
